### ISSUE TITLE
Instance reference in struct

### ISSUE THREAD

**Issue by j-klier** [SystemRDL/systemrdl-compiler#100]
I'm trying to create a struct with an instance reference as one of the members.  Table 7 says to use the keyword `ref`

```
struct submap_t {
    ref child_map;
    bit offset;
} ;
```

This results in a compile error.
```
extraneous input 'ref' expecting {'}', 'boolean', 'bit', 'longint', 'string', 'accesstype', 'addressingtype', 'onreadtype', 'onwritetype', 'addrmap', 'regfile', 'reg', 'field', 'mem', 'signal', ID}
    ref child_map;
    ^^^
```

Is this supported?

**Comment by amykyta3** [comment]
The `ref` keyword is not allowed in this situation. Instead, try one of the specific component type keywords like `reg`, `field`, etc...
That should work.

If you look at the formal grammar definition in annex B.4, struct elements are defined as follows:

```
struct_elem ::= struct_type id [ array_type ]
struct_type ::= data_type | component_type
...
component_type ::= component_primary_type | signal
component_primary_type ::= addrmap | regfile | reg | field | mem
```

I've found that the RDL spec is *extremely* inconsistent when it comes to the `ref` keyword. They prominently display it in Table 7,  but the only place the formal BNF grammar actually allows it is in user defined property definitions. Nowhere else!

**Comment by j-klier** [comment]
I've confirmed this works as expected.  Thanks!
```
struct submap_t {
    addrmap child_map;
    bit offset;
};
```
