### ISSUE TITLE
Linking between addrmap and its origin file

### ISSUE THREAD

**Issue by markcohen32** [SystemRDL/systemrdl-compiler#113]
Hi,

Is is possible to add to an addrmap a property which holds a value of its source file? i.e. , not a user-defined-property (exposed to the users) , but a property that can be accessed by the compiler's API?

Thanks

**Comment by amykyta3** [comment]
See issue #85 - that might have the information you are looking for.

Every node contains information about where it was defined, instantiated, and where each property was assigned.
This is all contained inside a "source reference" object. I have added more information here: https://systemrdl-compiler.readthedocs.io/en/latest/api/source_ref.html
