### ISSUE TITLE
Distributed registers

### ISSUE THREAD

**Issue by PRWald** [SystemRDL/systemrdl-compiler#117]
Hi Alex,
This isn't a bug report. It's just that you've been able to creatively solve tricky RDL problems I have had in the past, and now I've got another one. I know you are busy, so if you don't have time you can close this now with my apology for wasting your time.

The issue:
I have a design with lots of status bits distributed throughout the modules of the chip. These bits are logically all within a single register and do not overlap. Each module has its own bus interface. The busses from the various modules are combined at the top level, so when the register is read, multiple modules respond, each with a subset of the bits which combine to give the software one register value.

I can't see how to code this in RDL. It's not an alias (one physical register -- multiple logical addresses); it's sort of the opposite (one logical address -- multiple physical instances). If RDL would allow for multiple registers (of the same name) to be defined at the same address (but with non-overlapping fields) in different address maps, then this would work.

Is this a case for an "external" register? I don't understand much about "external" from the spec, so I can't tell.

Any insight would be greatly appreciated.

**Comment by amykyta3** [comment]
Yeah definitely sounds like an external register to me.
The mechanism that implements this aggregation data bus seems out of scope for the RDL language, so the best you can do is mark the register as external. That denotes that the register is of some user-defined implementation, or not handled in the usual scope of a code generator.

**Comment by PRWald** [comment]
Thank you.
