### ISSUE TITLE
Iterator that provides MemNodes?

### ISSUE THREAD

**Issue by kele14x** [SystemRDL/systemrdl-compiler#145]
Hi, is there any iterator that provides nodes for all immediate memory (MemNode) of component? Seems that there are function like `signals()`, `fields()`, `registers()`, but not memory.

**Comment by amykyta3** [comment]
I stopped adding those specialized methods because it is just as easy to use the generic `children()` iterator to do the following:
```python
for child in node.children():
    if not isinstance(child, MemNode):
        continue
    # after this, child is always MemNode
```

**Comment by kele14x** [comment]
Hi @amykyta3,

Thanks for your answer! I will try this way.
