### ISSUE TITLE
Assign array of inherited structures to an property with array of base structures

### ISSUE THREAD

**Issue by Risto97** [SystemRDL/systemrdl-compiler#161]
Hello,
I think I have found a corner case:

I create 2 structures, prop_base and prop_inherit which inherits prop_base.
Then also 2 properties, test_prop which is a single prop_base instance as type.
And also array_prop which holds an array of prop_base structures;

```
struct prop_base{
    string name;
};

struct prop_inherit : prop_base{
    string prefix;
};

property test_prop{
    component = addrmap;
    type = prop_base;
};

property array_prop{
    component = addrmap;
    type = prop_base[];
};

addrmap test {
    test_prop = prop_inherit'{name:"apb_bus", prefix:"asd"};
    array_prop = '{ 
        prop_inherit'{name:"apb_bus", prefix:"bcd"},  // prop_base would work
        prop_inherit'{name:"apb_bus", prefix:"bcd"}
        };

 reg {name = "dummy"; field {sw = r; hw = w;} dummy[1] = 0;} dummy;
};
```
I am able to assign inherited structure to the property with a base structure as type like the above and it works.
But with the array of structures, it is not possible with inherited structures. If I use prop_base instead it works.

Apart from 6.3.2.2.2 c) of the standard, I did not see any mention of this case.
But I would assume it should be allowed?

**Comment by amykyta3** [comment]
Yeah I agree this doesn't look right.
I actually found a similar bug last week that involved array-type user properties, so this might be related. Will fix!

**Comment by Risto97** [comment]
Another quick question, do you think the array of mixed inherited and base structs should be allowed?
Like this:
```
    array_prop = '{ 
        prop_base'{name:"apb_bus"},
        prop_inherit'{name:"apb_bus", prefix:"bcd"}
        };
```
It will trow an error that the array has to have the same types of elements, but maybe this case might be an exception?

**Comment by amykyta3** [comment]
Interesting question!
I'll have to look into that one. My hunch is that if `array_prop` is of type `prop_base[]` then it should be allowed.

**Comment by amykyta3** [comment]
Fixed all the issues mentioned in this thread in v1.25.5.

I had several layers of problems regarding user properties and aggregate datatypes. Should be better now.
Thanks for reporting this and providing excellent details!
