### ISSUE TITLE
Problem with error coordinates when `include is used.

### ISSUE THREAD

**Issue by eruanno123** [SystemRDL/systemrdl-compiler#21]
Hi,

I think there is a problem with line/column coordinates translation. The example attached below should fail due to missing semicolon. But the message printer would print something like:

```
examples/example_02/aaa.rdl:3:17: error: missing ';' at '}'
 *                 4
                 ^
```

I changed this line: https://github.com/SystemRDL/systemrdl-compiler/blob/78d6fdbb63ca4b22faab3d1e80682fc936c0f422/systemrdl/preprocessor/preprocessor.py#L84

To: 

```
pl_seg.start, pl_seg.end, pl_seg.file_pp.path,
```

I did not follow the full consequences of this change but at least I am getting correct message:

```
examples/example_02/bbb.rdl:5:4: error: missing ';' at '}'
    } CONTROL;
    ^
```

### File listings

> File `aaa.rdl` (it looks so, because I wanted to have 20 characters per row):
> 
> ```
> `include "bbb.rdl"//
> /*                 3
>  *                 4
>  *                 5
>  *                 6
>  *                 7
>  *                 8
>  *                 9
>  *                10
>  *                11
>  *                12
>  *              13*/
> ```
> 
> File `bbb.rdl`:
> 
> ```
> addrmap SYSTEM {
>     reg {
>         field {
>         } A
>     } CONTROL;
> };
> ```

**Comment by amykyta3** [comment]
Thanks!
And good find on the solution. That would have taken me a while to track down.

Unrelated: I noticed you're working on an RTL generator. While developing your register compiler, if you run into anything you'd like to see, I'd love to hear suggestions. Personally, I found that when I was writing the HTML and IP-XACT generators, it informed a few new features.
I noticed you wrapped in your own "debug" and "info" message severities. Good idea. I'll see how I can integrate that a little better on my end.

Cheers,
-Alex
