### ISSUE TITLE
`define for value replacement does not work

### ISSUE THREAD

**Issue by maltaisn** [SystemRDL/systemrdl-compiler#212]
I can use `` `define `` in conjunction with `` `ifdef ``, but it fails for any value replacement. Since this is not covered by tests, I assume macros with or without arguments are not yet implemented.
```
`define MACRO1 256
`define MACRO2(a) ((a)+1)
```

**Comment by amykyta3** [comment]
Not sure what you mean. Preprocessor macros have been supported for several years now and are [indeed covered by tests](https://github.com/SystemRDL/systemrdl-compiler/blob/main/test/test_preprocessor.py).

I just expanded your example and ran it through the preprocessor:
```
`define MACRO1 256
`define MACRO2(a) ((a)+1)

EXAMPLE1 `MACRO1
EXAMPLE2 `MACRO2(1234)
```

```
peakrdl preprocess test.rdl -o test.pp.rdl
```

Results in:
```
EXAMPLE1 256
EXAMPLE2 ((1234)+1)
```
