### ISSUE TITLE
[1.7.0] Cannot use `singlepulse` in RDL file due to incorrectly looked-up property.

### ISSUE THREAD

**Issue by eruanno123** [SystemRDL/systemrdl-compiler#23]
Hello again,

I think I have found one breaking change (one of my RDL description file did not compile):
https://github.com/SystemRDL/systemrdl-compiler/blob/6dbe34bf188e9582d2bfc04bb243db749fd437b4/systemrdl/core/properties.py#L865

I guess this is a semantic check against 9.6.1.g. Shouldn't it actually be `node.get_property('reset') != 0` ?

**Comment by amykyta3** [comment]
Thanks for reporting!
I just pushed another release that fixes it. (v1.7.1)
