### ISSUE TITLE
[BUG] concatenate enum to int fails

### ISSUE THREAD

**Issue by nachumg** [SystemRDL/systemrdl-compiler#230]
- [ ] I have reviewed this project's [contribution guidelines](https://github.com/SystemRDL/systemrdl-compiler/blob/main/CONTRIBUTING.md)

**Describe the bug**

Concatenation of enum to int fails compilation with an error.

* Sample SystemRDL code

```
addrmap top {
  enum x_enum {
    TWELVE = 8'd12 { desc = "Number twelve"; };
  };
  reg reg_t {
    field {} f[32];
  } some_reg;

  some_reg.f->reset = {x_enum::TWELVE, 8'hA, 16'hB};
};
```

* Error message
Elements of a concatenation shall be the same type

* Version numbers for the tool, Python, and OS
n/a

**Expected behavior**
Compilation success with correctly concatenated value assigned.
In the above example, assigned value should be 0xC0A000B

**Additional context**
None.

**Comment by amykyta3** [comment]
Fixed the bug, but I would not recommend directly concatenating enums like this.
Instead, it would be safer to explicitly cast the enum to the desired bitwidth, especially if the enum reference is not the leftmost item in the concatenation:
```
some_reg.f->reset = {8'hAB, (8)'(x_enum::TWELVE), 16'hB};
```
