### ISSUE TITLE
tree-sitter

### ISSUE THREAD

**Issue by drom** [SystemRDL/systemrdl-compiler#24]
I have implemented `tree-sitter` parser grammar for SystemRDL 2.0 here: https://github.com/drom/tree-sitter-systemrdl

And syntax highlighter for Atom base on `tree-sitter-systemrdl` : https://github.com/drom/language-systemrdl

I was wondering if you have any interest in trying it or/and moving into `SystemRDL` org?

**Comment by amykyta3** [comment]
Sounds great!
I have sent you an invite to the `SystemRDL` org. You should be able to transfer the repositories.

For the Atom plugin, I'd recommend renaming it to `atom-systemrdl` or similar so that it is less ambiguous.

**Comment by drom** [comment]
done.
