### ISSUE TITLE
[BUG] py.typed not being installed

### ISSUE THREAD

**Issue by krcb197** [SystemRDL/systemrdl-compiler#241]
- [x] I have reviewed this project's [contribution guidelines](https://github.com/SystemRDL/systemrdl-compiler/blob/main/CONTRIBUTING.md)

**Describe the bug**
The `py.typed` file is not being included in the distributed package

**Expected behavior**
The `py.typed` file should be installed when the package is installed

**Comment by amykyta3** [comment]
Should already be fixed, pending upcoming release which I expect to publish soon.

I had recently reworked the packaging to use setuptools-scm via pyproject.toml. This change will also correctly bundle the `py.typed` file into distributions.
