### ISSUE TITLE
Would like compiler to replace symbol in RDL with calculated address

### ISSUE THREAD

**Issue by PRWald** [SystemRDL/systemrdl-compiler#26]
This is a chicken and egg problem. I'd like a field's reset value be the compiler-calculated address of another register. Is this possible?

**Comment by amykyta3** [comment]
Reading through the [RDL spec](https://accellera.org/downloads/standards/systemrdl), I don't see anything in the language that directly implements what you're looking for.

The _closest_ thing would be to declare a user-defined property to mark the field with the special behavior, and implement whatever exporter you use to detect it and implement the field's reset value as you described.

**Comment by PRWald** [comment]
Okay, that's helpful. Thanks!
