### ISSUE TITLE
Minor documentation bug?

### ISSUE THREAD

**Issue by lurch** [SystemRDL/systemrdl-compiler#3]
In https://github.com/SystemRDL/systemrdl-compiler/blob/master/docs/model_structure.rst the text says:
```
addrmap top {
    my_reg_t A;
    my_reg_t B[4];
};
```
but then in the picture underneath it, it shows:
```
   A              B
 (reg)          (reg)
dim=[4]
```

Seems to be a mismatch about whether `A` or `B` is using an array?

**Comment by amykyta3** [comment]
Good catch. Thanks for reporting it!
