### ISSUE TITLE
Reset with signal reference returns RuntimeError

### ISSUE THREAD

**Issue by tolaszi** [SystemRDL/systemrdl-compiler#44]
When the reset is defined as signal reference as shown in example 8.3.2 below, the compiler raises a RuntimeError.

```
addrmap foo {
    reg { field {} a[8]=0; } reg1;
    signal { signalwidth=8;} mySig[8];
    reg1.a->reset = mySig; // Instead of resetting this field to a constant
                           // we connect it to a signal to provide an
                           // External reset value
};
```

When looking at the `validate` method of the `Prop_reset` class between lines 586-609 in the `systemrdl/core/properties.py` file it seems that the code handles the case when the reset is an int or a field node but passes to the else branch before handling the signal reference case.

**Comment by amykyta3** [comment]
Thanks for finding! Fixed.

**Comment by tolaszi** [comment]
Thanks!
