### ISSUE TITLE
How to provide a base address value

### ISSUE THREAD

**Issue by muneebullashariff** [SystemRDL/systemrdl-compiler#55]
addrmap test {
  reg
   ......
   .....
  } cfg1 @0x04;
};

In this the offset value for the register is 0x04.

I want to give the base address as 0x1000_0000 so that absolute address is 0x1000_0004
How to achieve this?

**Comment by amykyta3** [comment]
Since SystemRDL's global address space always starts at 0, you could instantiate your `test` addrmap inside a top-level block to define its absolute offset:
```
addrmap top {
    addrmap test {
        reg {
            // ....
        } cfg1 @0x04;
    };
    
    test test_inst @0x1000_0000;
};
```
