### ISSUE TITLE
PSS - Portable Stimulus compiler

### ISSUE THREAD

**Issue by muneebullashariff** [SystemRDL/systemrdl-compiler#57]
Hi Alex Mykyta,
I really like this systemrdl compiler that you have crafted. This has helped me a big time.

I want to request you to create a compiler for the PSS by accelera.
https://www.accellera.org/downloads/standards/portable-stimulus

This will be grear compiler for the open source for reusable test(s) generation.  I can work with you on this.

Let me know your thoughts on this.

**Comment by amykyta3** [comment]
I don't know that I have the time or energy to devote to this. Sorry :frowning_face: 
The SystemRDL compiler took me about 2 years to develop. This was all done in the evenings on my personal time, after an already demanding daytime job. Even now, it isn't totally feature-complete and I want to slowly expand the ecosystem of "PeakRDL" tools.

PSS looks like an interesting language, but it also seems to be _significantly_ more involved than SystemRDL, as it not simply a structural description language. I admit, I am far from an expert when it comes to building a compiler.

If you're interested in implementing it, I'd recommend reading the [Antlr book](https://pragprog.com/titles/tpantlr2/). It was a very useful reference that helped me get started with the SystemRDL compiler and understanding how parser-generators work. There are other parser-generators out there beyond Antlr, its just the one that seemed the most appropriate for RDL.
