### ISSUE TITLE
Doesn't support `define, `ifdef and `ifndef 

### ISSUE THREAD

**Issue by muneebullashariff** [SystemRDL/systemrdl-compiler#59]
Compiler throws an error when using the below:
 \`define, \`ifdef and \`ifndef 

Looks like only \`include is supported. Could you please support the above options too?

**Comment by amykyta3** [comment]
Already have a ticket for this under #41. Closing this as duplicate

**Comment by amykyta3** [comment]
fyi: will be implemented in next release - v1.13.0
