### ISSUE TITLE
Drop support for Python 3.4

### ISSUE THREAD

**Issue by amykyta3** [SystemRDL/systemrdl-compiler#61]
Python 3.4 [has reached end-of-life on 2019-03-08](https://www.python.org/downloads/release/python-3410/) and has largely been phased out by now.

I also do not publish binary distributions for 3.4, nor do I run unit tests, so support for it is already quite spotty.
Remove any compatibility backports that were added to fix #14 #15 #16 

@Muffo any concerns? You had originally opened #14 and #15.

**Comment by Muffo** [comment]
No problem from my side. I am not actively using the project at the moment, but thanks for asking.
