### ISSUE TITLE
reset value for array 

### ISSUE THREAD

**Issue by soleshka** [SystemRDL/systemrdl-compiler#63]
Hello,
I have found this compiler a very useful for my register description.
The only issue i hit is how to reset an array  ? 

I ma trying to do something like:

				reg R003_IPATOV {
					name = "R003_IPATOV";
					hdl_path   	= "";
					field {name = "field1";} field1[31:0]=0x0;
				}R003_IPATOV[8] = '{};

But i fail on compilation.

Is this doable ? 

Thank you for the prompt response,
Oleg

**Comment by amykyta3** [comment]
Since you already provide a reset value for `field1`, there is no need to provide a reset value for the array of registers.
In SystemRDL, reset values are only defined for the individual fields, since registers are simply a collection of fields.

**Comment by soleshka** [comment]
Thank you for your prompt response. So please correct me once more, there
is no option to reset array elements with different values? I.e '{1,2,3,4..}
Thank you,
Oleg

Alex Mykyta <notifications@github.com> schrieb am Mi., 23. Sept. 2020,
07:36:

**Comment by amykyta3** [comment]
Not at the moment. The SystemRDL spec does describe the ability to do this, but this compiler does not support this yet. I may extend support for this feature in the future. See the discussion in #51 

Example: (Not supported by this compiler yet)
```
reg R003_IPATOV {
    field {} field1[31:0] = 0x0;
} R003_IPATOV[8];

R003_IPATOV[0].field1->reset = 1;
R003_IPATOV[1].field1->reset = 2;
R003_IPATOV[2].field1->reset = 3;
R003_IPATOV[3].field1->reset = 4;
```
