### ISSUE TITLE
Suggest different color for messages

### ISSUE THREAD

**Issue by kjeldbeg** [SystemRDL/systemrdl-compiler#71]
In messages.py the foreground color is Fore.WHITE for file name/line number. Unfortunately this makes the text invisible on a standard xterm. I suggest you change the color to Fore.BLUE.

**Comment by amykyta3** [comment]
I'll remove the white styling entirely and instead only have that portion be bold. That way it'll match the color scheme that your xterm is configured to. Will be reflected in the upcoming v1.15 release.

In the meantime, you should check your xterm color palette. Most themes will override certain colors to prevent situations like this (eg: white on white background)

**Comment by kjeldbeg** [comment]
Thank you.
