### ISSUE TITLE
Cannot assign reference to hwset and wel

### ISSUE THREAD

**Issue by kjeldbeg** [SystemRDL/systemrdl-compiler#73]
This is related to #31.

I specifically need to assign a reference to the wel and hwset properties.

I can see the compiler accepts assignment of a reference to reset, enable, hwmask and many more. How come assignment of a reference is not accepted for we, wel, hwclr, hwset?

**Comment by amykyta3** [comment]
Good find. For some reason I have these properties set to only accept boolean values, when Table G1 in the spec clearly show that instance references are also valid assignments.

**Comment by amykyta3** [comment]
fixed in v1.15.1

**Comment by kjeldbeg** [comment]
Thank you.
