### ISSUE TITLE
Global default accesswidth is lost

### ISSUE THREAD

**Issue by kjeldbeg** [SystemRDL/systemrdl-compiler#95]
I compile two files (with compile_file()) and use elaborate() on the root addrmap. The first file has the (root) line:

`default accesswidth = 32;`

but unfortunately this default only affects the contents of the first file. Is this the expected behaviour?

**Comment by amykyta3** [comment]
This is intentional. See
https://systemrdl-compiler.readthedocs.io/en/latest/dev_notes/multi_file_compilation.html#default-property-assignments-are-limited-to-the-compilation-unit

**Comment by kjeldbeg** [comment]
Thanks for the clarification.
