### ISSUE TITLE
Overlapping two reg arrays

### ISSUE THREAD

**Issue by markcohen32** [SystemRDL/systemrdl-compiler#99]
Hi,

I'm trying to instantiate two or more reg arrays with strides that should not overlap each other in the following way:

```
reg {
    regwidth =32;
    // reg content
} FIRST__REG_ARRAY[2] @0x0 += 0x8;

reg {
    regwidth =32;
    // reg content
} SECOND_REG_ARRAY[2] @0x4 +=0x8 ;
```
Which means, that the first reg of the **first** array should be located at 0x0, the first reg of the **second** array at 0x4 and thus on, since each one of them is exactly 32 bits . But, I get an error of overlapping. Does it mean that this cannot be done or am I doing something wrong here?

Thanks

**Comment by amykyta3** [comment]
The compiler does not support interleaving register arrays. See a similar question #8.
